### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by ghutchis** [pittquantum/PittQuantumRepository#53]
This is more for the pqr.pitt.edu instance - we need to generate the CSR on the server and get a signed SSL certificate.

**Comment by JoshuaRogan** [comment]
Where do we stand with this? 

I tested with some online tools and saw this:
"The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider."

**Comment by ghutchis** [comment]
The first thing was CSSD opening the firewall for HTTPS, which clearly now works.

@RitwikGupta and I used the server cert alone, because the original cert didn't match the order expected by nginix. I tried catenating the certs together and that caused problems. It's shouldn't take more than 30 minutes to fix it now the firewall is open.

**Comment by RitwikGupta** [comment]
Fixed! https://pqr.pitt.edu
